In [1]:
import statistics as st
import numpy as np
from matplotlib import pyplot as plt

## Questão 2

Os cálculos da questão 2 foram executados aqui apenas para fins de confirmação dos resultados, visto que a resolução final foi realizada através da transformação linear, como descrito no pdf.

In [2]:
X = list(range(1000,10001, 5))

In [3]:
Xarray = np.array(X)

print("Série")
print(Xarray)

Série
[ 1000  1005  1010 ...  9990  9995 10000]


In [4]:
Y = [x/5 - 199 for x in X]
Yarray = np.array(Y)

print("Série resultado da transformação")
print(Yarray)

Série resultado da transformação
[1.000e+00 2.000e+00 3.000e+00 ... 1.799e+03 1.800e+03 1.801e+03]


In [5]:
S = Xarray[:,None] - Xarray

print("Valores obitidos pela subtração X - X")
print(S)
print()
print("Máx =", np.max(S))
print("Min =", np.min(S))
print()
print("Média =", np.mean(S))
print("Variancia =", np.var(S))

Valores obitidos pela subtração X - X
[[    0    -5   -10 ... -8990 -8995 -9000]
 [    5     0    -5 ... -8985 -8990 -8995]
 [   10     5     0 ... -8980 -8985 -8990]
 ...
 [ 8990  8985  8980 ...     0    -5   -10]
 [ 8995  8990  8985 ...     5     0    -5]
 [ 9000  8995  8990 ...    10     5     0]]

Máx = 9000
Min = -9000

Média = 0.0
Variancia = 13515000.0


## Questão 4

### Item A

In [6]:
# Definição da série
Z = []
for i in range(20):
    Z.append(1)
    Z.append(5)
for i in range(60):
    Z.append(10)
    
Z.sort()

In [7]:
# Criação de um array baseado na série
Zarray = np.array(Z)

print("Série")
print(Zarray)

Série
[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  5  5  5  5
  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5 10 10 10 10 10 10 10 10
 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
 10 10 10 10]


In [8]:
# Para não fazer uso apenas das funções já prontas da biblioteca, a média abaixo foi
# calculada via equação passada em aula (apenas como exercício).
Z_valores, Z_propabilidades = np.unique(Zarray, return_counts=True)
Media_Z = (Z_valores * Z_propabilidades/Zarray.size).sum()

print("Série original:")
print("Média =", Media_Z)
print("Mediana =", np.median(Zarray))
print("Moda =", st.mode(Zarray))

Série original:
Média = 7.2
Mediana = 10.0
Moda = 10


### Item B

In [9]:
# Copiar série
Zarray_novo = np.copy(Zarray)

# Substituir um dos valores [1] por [1000]
Zarray_novo[0] = 1000

# Ordenar série modificada
Zarray_novo = np.sort(Zarray_novo)

print("Série depois da modificação")
print(Zarray_novo)

Série depois da modificação
[   1    1    1    1    1    1    1    1    1    1    1    1    1    1
    1    1    1    1    1    5    5    5    5    5    5    5    5    5
    5    5    5    5    5    5    5    5    5    5    5   10   10   10
   10   10   10   10   10   10   10   10   10   10   10   10   10   10
   10   10   10   10   10   10   10   10   10   10   10   10   10   10
   10   10   10   10   10   10   10   10   10   10   10   10   10   10
   10   10   10   10   10   10   10   10   10   10   10   10   10   10
   10 1000]


In [10]:
print("Série modificada:")
print("Média =", np.mean(Zarray_novo))
print("Mediana =", np.median(Zarray_novo))
print("Moda =", st.mode(Zarray_novo))

Série modificada:
Média = 17.19
Mediana = 10.0
Moda = 10


### Item C

In [11]:
print("Desvio padrão da série original =",np.std(Zarray))
print("Desvio padrão da série modificada =",np.std(Zarray_novo))

Desvio padrão da série original = 3.655133376499413
Desvio padrão da série modificada = 98.84176192278241
